name: Release

on:
  workflow_dispatch:
  release:
    types: published
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configure Java 8 and generate a settings.xml file containing the OSSRH credentials
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: OSSRH_GPG_PASSPHRASE

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
         JF_URL: ${{ vars.ARTIFACTORY_URL }}
         JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Scan with jfrog audit
        run: jfrog audit

      # Run mvn install
      - name: Install
        run: mvn install -B

      # Deploy to Maven Central
      - name: Deploy to Maven Central
        run: mvn -B deploy -Pupload-to-central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
